export { Hero } from "./Hero";
export { HeroSearch } from "./HeroSearch";
export { HeroSlider } from "./HeroSlider";
export { CategoriesShowcase } from "./CategoriesShowcase";
export { FeaturedServices } from "./FeaturedServices";
export { FeaturedFreelancers } from "./FeaturedFreelancers";
export { HowItWorks } from "./HowItWorks";
export { Testimonials } from "./Testimonials";
export { FinalCallToAction } from "./FinalCallToAction";
